<?php
/**
 * Generate poweradmin-mysql-geoip-data.sql from MaxMind GeoIP2-City
 * Locations CSVs.
 *
 * Usage:
 *   php install/helpers/generate_geoip_sql.php \
 *       --en /path/to/GeoIP2-City-Locations-en.csv \
 *       --zh /path/to/GeoIP2-City-Locations-zh-CN.csv \
 *       --isp /path/to/GeoIP2-ISP-Blocks-IPv4.csv \
 *       --domain /path/to/GeoIP2-Domain-Blocks-IPv4.csv \
 *       --out sql/poweradmin-mysql-geoip-data.sql
 *
 * --en is required (City Locations English). All others are optional:
 *   --zh produces name_zh columns.
 *   --isp dedupes the ISP column from GeoIP2-ISP-Blocks into geo_isps
 *         (~75k rows) for the Line=ISP type-ahead picker.
 *   --domain does the same for GeoIP2-Domain-Blocks into geo_domains.
 *
 * The script streams the large CSVs row-by-row to keep memory bounded
 * around ~50MB. The ZH lookup is compact (geoname_id → 4-tuple).
 *
 * Output tables (must already exist; created by
 * sql/poweradmin-mysql-geoip-routing.sql):
 *   geo_continents, geo_countries, geo_regions, geo_cities, geo_isps, geo_domains
 */

declare(strict_types=1);

const BATCH = 500;

function parseArgs(array $argv): array
{
    $opts = ['en' => null, 'zh' => null, 'isp' => null, 'domain' => null, 'out' => null];
    for ($i = 1; $i < count($argv); $i++) {
        $a = $argv[$i];
        $next = $argv[$i + 1] ?? null;
        switch ($a) {
            case '--en':     $opts['en']     = $next; $i++; break;
            case '--zh':     $opts['zh']     = $next; $i++; break;
            case '--isp':    $opts['isp']    = $next; $i++; break;
            case '--domain': $opts['domain'] = $next; $i++; break;
            case '--out':    $opts['out']    = $next; $i++; break;
            case '-h':
            case '--help':
                fwrite(STDERR, file_get_contents(__FILE__, false, null, 0, 1800));
                exit(0);
            default:
                fwrite(STDERR, "Unknown arg: $a\n");
                exit(2);
        }
    }
    if (!$opts['en'] || !$opts['out']) {
        fwrite(STDERR, "Missing required --en or --out.\n");
        exit(2);
    }
    foreach (['en', 'zh', 'isp', 'domain'] as $k) {
        if ($opts[$k] !== null && !is_readable($opts[$k])) {
            fwrite(STDERR, "Cannot read --$k file: {$opts[$k]}\n");
            exit(2);
        }
    }
    return $opts;
}

function openCsv(string $path): array
{
    $fh = fopen($path, 'r');
    if (!$fh) { fwrite(STDERR, "Cannot open $path\n"); exit(1); }
    $header = fgetcsv($fh);
    if (!$header) { fwrite(STDERR, "Empty file: $path\n"); exit(1); }
    $idx = array_flip($header);
    $required = [
        'geoname_id', 'continent_code', 'continent_name',
        'country_iso_code', 'country_name',
        'subdivision_1_iso_code', 'subdivision_1_name', 'city_name',
    ];
    foreach ($required as $col) {
        if (!isset($idx[$col])) {
            fwrite(STDERR, "Missing column '$col' in $path\n");
            exit(1);
        }
    }
    return [$fh, $idx];
}

/** Compact ZH lookup: geoname_id => "$continent\t$country\t$region\t$city". */
function loadZhLookup(string $path): array
{
    [$fh, $idx] = openCsv($path);
    $out = [];
    while (($r = fgetcsv($fh)) !== false) {
        $gid = $r[$idx['geoname_id']] ?? '';
        if ($gid === '') continue;
        $out[$gid] = ($r[$idx['continent_name']]       ?? '') . "\t"
                   . ($r[$idx['country_name']]         ?? '') . "\t"
                   . ($r[$idx['subdivision_1_name']]   ?? '') . "\t"
                   . ($r[$idx['city_name']]            ?? '');
    }
    fclose($fh);
    return $out;
}

function q($v): string
{
    if ($v === null || $v === '') return 'NULL';
    return "'" . str_replace(["\\", "'"], ["\\\\", "\\'"], (string)$v) . "'";
}

class BatchWriter {
    private $fh;
    private string $table;
    private array $columns;
    private array $buf = [];

    public function __construct($fh, string $table, array $columns)
    {
        $this->fh = $fh;
        $this->table = $table;
        $this->columns = $columns;
    }

    public function add(array $row): void
    {
        $this->buf[] = '(' . implode(',', $row) . ')';
        if (count($this->buf) >= BATCH) $this->flush();
    }

    public function flush(): void
    {
        if (!$this->buf) return;
        $cols = implode(',', array_map(fn($c) => "`$c`", $this->columns));
        fwrite($this->fh, "INSERT INTO `{$this->table}` ($cols) VALUES\n");
        fwrite($this->fh, implode(",\n", $this->buf));
        fwrite($this->fh, ";\n");
        $this->buf = [];
    }
}

$opts = parseArgs($argv);

$zhLookup = [];
if ($opts['zh']) {
    fwrite(STDERR, "Loading ZH lookup: {$opts['zh']}\n");
    $zhLookup = loadZhLookup($opts['zh']);
    fwrite(STDERR, "  zh rows: " . count($zhLookup) . "\n");
}

$out = fopen($opts['out'], 'w');
if (!$out) { fwrite(STDERR, "Cannot write {$opts['out']}\n"); exit(1); }

fwrite($out, "-- Generated by install/helpers/generate_geoip_sql.php\n");
fwrite($out, "-- Source: " . basename($opts['en']));
if ($opts['zh']) fwrite($out, " + " . basename($opts['zh']));
fwrite($out, "\nSET NAMES utf8mb4;\nSET autocommit=0;\nSTART TRANSACTION;\n\n");

// Per-table batch writers
$wContinents = new BatchWriter($out, 'geo_continents', ['code', 'name_en', 'name_zh']);
$wCountries  = new BatchWriter($out, 'geo_countries',  ['iso_code', 'continent_code', 'name_en', 'name_zh']);
$wRegions    = new BatchWriter($out, 'geo_regions',    ['country_iso', 'region_code', 'name_en', 'name_zh']);
$wCities     = new BatchWriter($out, 'geo_cities',     ['geoname_id', 'country_iso', 'region_code', 'name_en', 'name_zh']);

// Dedupe trackers (cheap string sets)
$seenContinent = [];
$seenCountry   = [];
$seenRegion    = [];
$cityCount = 0;

fwrite(STDERR, "Streaming EN: {$opts['en']}\n");
[$fh, $idx] = openCsv($opts['en']);
while (($r = fgetcsv($fh)) !== false) {
    $gid = $r[$idx['geoname_id']] ?? '';
    if ($gid === '') continue;
    $cc = $r[$idx['continent_code']]   ?? '';
    $co = $r[$idx['country_iso_code']] ?? '';
    $rc = $r[$idx['subdivision_1_iso_code']] ?? '';

    $zhParts = isset($zhLookup[$gid]) ? explode("\t", $zhLookup[$gid]) : ['', '', '', ''];
    [$contZh, $countryZh, $regionZh, $cityZh] = $zhParts;

    if ($cc !== '' && !isset($seenContinent[$cc])) {
        $seenContinent[$cc] = true;
        $wContinents->add([q($cc), q($r[$idx['continent_name']] ?: $cc), q($contZh ?: null)]);
    }
    if ($co !== '' && !isset($seenCountry[$co])) {
        $seenCountry[$co] = true;
        $wCountries->add([q($co), q($cc), q($r[$idx['country_name']] ?: $co), q($countryZh ?: null)]);
    }
    if ($co !== '' && $rc !== '') {
        $rkey = "$co:$rc";
        if (!isset($seenRegion[$rkey])) {
            $seenRegion[$rkey] = true;
            $wRegions->add([q($co), q($rc), q($r[$idx['subdivision_1_name']] ?: $rc), q($regionZh ?: null)]);
        }
    }
    $cityName = $r[$idx['city_name']] ?? '';
    if ($cityName !== '') {
        $cityCount++;
        $wCities->add([
            (string)(int)$gid,
            q($co),
            q($rc !== '' ? $rc : null),
            q($cityName),
            q($cityZh ?: null),
        ]);
    }
}
fclose($fh);

$wContinents->flush();
$wCountries->flush();
$wRegions->flush();
$wCities->flush();

// ---- ISP / Domain dedup tables (optional inputs) -------------------------
function emitDistinctNames($out, string $table, string $csvPath, int $column): int
{
    $fh = fopen($csvPath, 'r');
    if (!$fh) { fwrite(STDERR, "Cannot open $csvPath\n"); return 0; }
    // First row is header; skip.
    fgetcsv($fh);
    $seen = [];
    $skipped = 0;
    while (($r = fgetcsv($fh)) !== false) {
        $name = $r[$column] ?? '';
        if ($name === '') continue;
        // MaxMind ISP/Domain feeds occasionally contain double-encoded or
        // truncated multibyte sequences. MySQL refuses these in utf8mb4
        // columns, so drop them at generation time.
        if (!mb_check_encoding($name, 'UTF-8')) {
            $skipped++;
            continue;
        }
        $lower = mb_strtolower($name, 'UTF-8');
        if (isset($seen[$lower])) continue;
        $seen[$lower] = $name;
    }
    fclose($fh);
    if ($skipped > 0) {
        fwrite(STDERR, "  skipped $skipped rows with invalid UTF-8\n");
    }
    ksort($seen);

    $w = new BatchWriter($out, $table, ['name', 'name_lower']);
    foreach ($seen as $lower => $name) {
        $w->add([q($name), q($lower)]);
    }
    $w->flush();
    return count($seen);
}

$ispCount = 0;
if ($opts['isp']) {
    fwrite(STDERR, "Building geo_isps from {$opts['isp']}\n");
    // ISP blocks CSV: network,isp,organization,asn,aso,mcc,mnc — column index 1
    $ispCount = emitDistinctNames($out, 'geo_isps', $opts['isp'], 1);
}

$domainCount = 0;
if ($opts['domain']) {
    fwrite(STDERR, "Building geo_domains from {$opts['domain']}\n");
    // Domain blocks CSV: network,domain — column index 1
    $domainCount = emitDistinctNames($out, 'geo_domains', $opts['domain'], 1);
}

fwrite($out, "\nCOMMIT;\n");
fclose($out);

fwrite(STDERR, sprintf(
    "Wrote %s — %d continents, %d countries, %d regions, %d cities, %d isps, %d domains\n",
    $opts['out'],
    count($seenContinent), count($seenCountry), count($seenRegion), $cityCount,
    $ispCount, $domainCount
));
